version: '3.8'

services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sacsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://sacs:bonheur@postgres:5432/sacsdb
    depends_on:
      - postgres

volumes:
  pgdata:
