services:
  postgres:
    container_name: sacsabonheur_postgres
    image: postgres:17
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: sacsabonheur_backend
    build: ./backend
    volumes:
      - ./backend/public/uploads:/app/public/uploads
    ports:
      - "3001:3001"
      - "5555:5555"
    environment:
      DATABASE_URL: ${POSGRES_DATABASE_URL}
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local
