FROM node:22-bookworm-slim

RUN apt-get update -y && \
    apt-get install -y openssl libssl-dev ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

COPY entrypoint.sh ./
RUN chmod +x ./entrypoint.sh

EXPOSE 3001
CMD ["bash", "./entrypoint.sh"]
