FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate

COPY entrypoint.sh ./
RUN chmod +x ./entrypoint.sh

EXPOSE 3001
ENTRYPOINT ["bash", "./entrypoint.sh"]
