FROM node:22.16-alpine

RUN apk add --no-cache openssl ca-certificates bash

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

COPY entrypoint.sh ./
RUN chmod +x ./entrypoint.sh

EXPOSE 3001
CMD ["bash", "./entrypoint.sh"]
